---
site_name: Mewicli
theme:
  name: readthedocs

nav:
  - index.md
  - mewicli.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_bases: false
            show_source: false
            heading_level: 3
